[project]
name = "runi-thesis-research"
version = "0.1.0"
description = "A short description of the project."
readme = "README.md"
dependencies = []


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
